name: Create File in Repo

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Tên file (bao gồm đuôi mở rộng)'
        required: true
        default: 'file.txt'
      filepath:
          description: 'Đường dẫn folder chứa file (chọn một trong các folder dưới đây hoặc nhập tay)'
          required: true
          default: 'aplicas/ios'
          options:
            - aplicas/ios
            - aplicas/android
            - weplcas
      filecontent:
        description: 'Nội dung file'
        required: true
        default: 'File được tạo bởi GitHub Action'

permissions:
  contents: write

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (preserve credentials)
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # <-- very important for git push
          fetch-depth: 0

      - name: Create file with content
        run: |
          mkdir -p "${{ github.event.inputs.filepath }}"
          echo "${{ github.event.inputs.filecontent }}" > "${{ github.event.inputs.filepath }}/${{ github.event.inputs.filename }}"

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit if changed
        run: |
          git add "${{ github.event.inputs.filepath }}/${{ github.event.inputs.filename }}"
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Tạo file ${{ github.event.inputs.filename }} tại ${{ github.event.inputs.filepath }} qua Action"
          fi

      - name: Push changes to main
        run: |
          # Push current HEAD to main (will use GITHUB_TOKEN because persist-credentials: true)
          git push origin HEAD:main || (echo "Push failed — maybe branch protected or permission denied" && exit 1)
